# Generated by Django 2.2 on 2019-12-26 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Админпоз')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='accounts.Role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdminPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='accounts.AdminPosition', verbose_name='Админпоз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(max_length=30, verbose_name='Серия')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('inn', models.IntegerField(max_length=50, verbose_name='ИНН')),
                ('nationality', models.CharField(max_length=30, verbose_name='Национальность')),
                ('sex', models.CharField(max_length=15, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата Рождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL, verbose_name='Паспорт')),
            ],
        ),
    ]
