# Generated by Django 2.2 on 2019-12-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminposition_passport_role_useradminposition_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.IntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.IntegerField(verbose_name='Серия'),
        ),
    ]
