# Generated by Django 2.2 on 2019-12-26 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191226_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(max_length=15, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
