# Generated by Django 2.2 on 2020-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Социальный статус')),
            ],
        ),
    ]
