# Generated by Django 2.2 on 2019-12-26 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20191226_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socstatus', to='accounts.Role', verbose_name='Cтатус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socstatus', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
