# Generated by Django 2.2 on 2020-01-28 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_socialstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Номер телеофона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Фото')),
                ('address_fact', models.CharField(max_length=100, verbose_name='Фактический Адрес')),
                ('admin_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_position', to='accounts.AdminPosition', verbose_name='Должность')),
                ('role', models.ManyToManyField(related_name='role', to='accounts.Role', verbose_name='Роль')),
                ('social_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_status', to='accounts.SocialStatus', verbose_name='Соц. Статус')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='accounts.Status', verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
