# Generated by Django 2.2 on 2020-01-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(default='Кыргызская Республика', max_length=20, verbose_name='Гражданство')),
                ('series', models.CharField(max_length=15, verbose_name='Серия')),
                ('issued_by', models.CharField(blank='True', max_length=255, null='True', verbose_name='Кем выдан')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('inn', models.CharField(blank='True', max_length=50, null='True', verbose_name='ИНН')),
                ('nationality', models.CharField(blank='True', max_length=30, null='True', verbose_name='Национальность')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=15, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата Рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
