# Generated by Django 2.2 on 2020-01-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='accounts.AdminPosition', verbose_name='Админпоз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
