# Generated by Django 2.2 on 2020-01-08 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20191226_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_one', to=settings.AUTH_USER_MODEL, verbose_name='Родитель 1')),
            ],
        ),
        migrations.CreateModel(
            name='ParentTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_two', to=settings.AUTH_USER_MODEL, verbose_name='Родитель 2')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='accounts.Passport', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_one', to='accounts.ParentOne', verbose_name='Родитель Один'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_two', to='accounts.ParentTwo', verbose_name='Родитель Два'),
        ),
    ]
