# Generated by Django 2.2 on 2020-01-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191226_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminposition',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
    ]
