# Generated by Django 2.2 on 2020-01-08 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200108_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_two', to=settings.AUTH_USER_MODEL, verbose_name='Родитель Два'),
        ),
    ]
