# Generated by Django 2.2 on 2020-01-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200108_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='user',
        ),
    ]
