# Generated by Django 2.2 on 2020-01-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200108_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_one', to=settings.AUTH_USER_MODEL, verbose_name='Родитель Один'),
        ),
    ]
