# Generated by Django 2.2 on 2020-02-06 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200131_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passport',
            name='citizenship',
            field=models.CharField(default='Кыргызская Республика', max_length=50, verbose_name='Гражданство'),
        ),
    ]
