# Generated by Django 2.2 on 2020-02-14 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20200206_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user', to=settings.AUTH_USER_MODEL, verbose_name='Родственники')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_family', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Номер телефона'),
        ),
    ]
