# Generated by Django 2.2 on 2020-01-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_passport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_one', to='accounts.ParentOne', verbose_name='Родитель Один'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_two', to='accounts.ParentTwo', verbose_name='Родитель Два'),
        ),
    ]
