# Generated by Django 2.2 on 2020-02-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200206_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
