# Generated by Django 2.2 on 2020-01-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200109_0049'),
        ('accounts', '0007_auto_20200107_1452'),
    ]

    operations = [
    ]
