# Generated by Django 2.2 on 2020-01-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200108_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='accounts.Passport', verbose_name='Паспорт'),
        ),
    ]
