# Generated by Django 2.2 on 2020-01-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20200110_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent_one',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent_two',
        ),
        migrations.AlterField(
            model_name='passport',
            name='sex',
            field=models.CharField(choices=[('man', 'мужской'), ('women', 'женский')], max_length=15, verbose_name='Пол'),
        ),
        migrations.DeleteModel(
            name='UserSocialStatus',
        ),
    ]
