# Generated by Django 2.2 on 2020-01-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200110_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Статус')),
            ],
        ),
        migrations.AlterField(
            model_name='socialstatus',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Социальный статус'),
        ),
    ]
