# Generated by Django 2.2 on 2020-01-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200108_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passport',
        ),
    ]
