# Generated by Django 2.2 on 2020-02-19 12:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200217_1028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20200217_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudyGroup',
        ),
    ]
