# Generated by Django 2.2 on 2020-01-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20200110_0722'),
        ('accounts', '0013_auto_20200113_0925'),
    ]

    operations = [
    ]
