# Generated by Django 2.2 on 2020-01-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_group'),
        ('accounts', '0014_auto_20200116_0624'),
        ('accounts', '0014_auto_20200116_0644'),
    ]

    operations = [
    ]
