# Generated by Django 2.2 on 2020-02-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200219_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='starosta',
            new_name='group_leader',
        ),
    ]
