# Generated by Django 2.2 on 2020-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200116_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(related_name='role', to='accounts.Role', verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
