# Generated by Django 2.2 on 2020-01-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20200117_0744'),
        ('accounts', '0015_merge_20200120_0650'),
    ]

    operations = [
    ]
