# Generated by Django 2.2 on 2020-02-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200219_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='kurator',
            new_name='head_teaher',
        ),
    ]
