# Generated by Django 2.2 on 2020-01-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20200117_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='accounts.Status', verbose_name='Статус'),
        ),
    ]
