# Generated by Django 2.2 on 2020-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='citizenship',
            field=models.CharField(default='Кыргызстан', max_length=20),
        ),
    ]
