# Generated by Django 2.2 on 2020-01-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_passport_citizenship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminposition',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='adminposition',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Должность'),
        ),
    ]
