# Generated by Django 2.2 on 2020-01-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200120_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_position', to='accounts.AdminPosition', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
