# Generated by Django 2.2 on 2020-01-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_admin_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_position', to='accounts.AdminPosition', verbose_name='Должность'),
        ),
    ]
