# Generated by Django 2.2 on 2020-01-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200120_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_status', to='accounts.SocialStatus', verbose_name='Соц. Статус'),
        ),
    ]
