# Generated by Django 2.2 on 2020-01-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_social_status'),
        ('accounts', '0017_auto_20200122_0810'),
    ]

    operations = [
    ]
