# Generated by Django 2.2 on 2020-01-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200122_0810'),
        ('accounts', '0023_profile_social_status'),
        ('accounts', '0015_merge_20200122_1436'),
    ]

    operations = [
    ]
