# Generated by Django 2.2 on 2020-01-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_merge_20200123_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='citizenship',
            field=models.CharField(default='Кыргызстан', max_length=20),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicipline', to='webapp.Discipline', verbose_name='Дисциплина')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='webapp.Grade', verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='accounts.Theme', verbose_name='Тема')),
            ],
        ),
    ]
