# Generated by Django 2.2 on 2020-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20200123_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='citizenship',
            field=models.CharField(default='Кыргызстан', max_length=20),
        ),
    ]
