# Generated by Django 2.2 on 2020-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20200122_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='sex',
            field=models.CharField(choices=[('man', 'мужской'), ('women', 'женский')], default='man', max_length=15, verbose_name='Пол'),
        ),
    ]
