# Generated by Django 2.2 on 2020-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200124_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='sex',
            field=models.CharField(choices=[('man', 'мужской'), ('women', 'женский')], max_length=15, verbose_name='Пол'),
        ),
    ]
