# Generated by Django 2.2 on 2020-01-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200122_0648'),
        ('accounts', '0025_auto_20200122_1233'),
    ]

    operations = [
    ]
