# Generated by Django 2.2 on 2020-01-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20200123_0646'),
        ('accounts', '0027_auto_20200124_1124'),
        ('accounts', '0025_auto_20200123_1550'),
    ]

    operations = [
    ]
