# Generated by Django 2.2 on 2020-01-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_merge_20200127_1831'),
        ('accounts', '0025_auto_20200123_1011'),
    ]

    operations = [
    ]
