# Generated by Django 2.2 on 2020-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.IntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
        ),
    ]
