# Generated by Django 2.2 on 2020-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.IntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
            ],
        ),
    ]
