# Generated by Django 2.2 on 2020-01-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auditory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditory',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='auditory',
            name='places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вместимость'),
        ),
    ]
