# Generated by Django 2.2 on 2020-01-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
