# Generated by Django 2.2 on 2020-01-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_grade_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
