# Generated by Django 2.2 on 2020-01-28 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ManyToManyField(related_name='disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
