# Generated by Django 2.2 on 2020-01-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
