# Generated by Django 2.2 on 2020-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.CharField(default=None, max_length=100, verbose_name='Событие'),
        ),
    ]
