# Generated by Django 2.2 on 2020-01-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_saturdaylesson_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='index',
            field=models.IntegerField(verbose_name='Порядковый номер'),
        ),
    ]
