# Generated by Django 2.2 on 2020-01-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_schedule_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
    ]
