# Generated by Django 2.2 on 2020-01-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200130_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saturdaylesson',
            name='name',
        ),
    ]
