# Generated by Django 2.2 on 2020-01-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_saturdaylesson'),
        ('webapp', '0012_remove_schedule_event'),
    ]

    operations = [
    ]
