# Generated by Django 2.2 on 2020-01-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200130_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='saturdaylesson',
            name='is_saturday',
            field=models.BooleanField(default=False, verbose_name='Суббота'),
        ),
    ]
