# Generated by Django 2.2 on 2020-01-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_saturdaylesson_is_saturday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_saturday',
            field=models.BooleanField(default=False, verbose_name='Суббота'),
        ),
    ]
