# Generated by Django 2.2 on 2020-01-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200130_0417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaturdayLesson',
        ),
    ]
