# Generated by Django 2.2 on 2020-02-14 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200214_1144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0019_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('lesson', 'day', 'group'), ('lesson', 'day', 'teacher'), ('lesson', 'day', 'auditoriya')},
        ),
    ]
