# Generated by Django 2.2 on 2020-02-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_discipline', to='webapp.Discipline', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='webapp.Discipline', verbose_name='Дисциплина'),
        ),
    ]
