# Generated by Django 2.2 on 2020-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20200214_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date']},
        ),
    ]
