# Generated by Django 2.2 on 2020-02-28 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0022_groupjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Тема или название занятия')),
            ],
        ),
    ]
