# Generated by Django 2.2 on 2020-03-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0022_groupjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('theme', models.CharField(max_length=100, verbose_name='Название занятия/Тема')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('group_journal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_journal_note', to='webapp.GroupJournal', verbose_name='Журнал группы по дисциплине')),
            ],
        ),
    ]
