# Generated by Django 2.2 on 2020-02-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_journalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalnote',
            name='group_journal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_journal_note', to='webapp.GroupJournal', verbose_name='Журнал группы по дисциплине'),
        ),
    ]
