# Generated by Django 2.2 on 2020-03-03 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0023_journalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем поставлена')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_grade', to='webapp.Grade', verbose_name='Оценка')),
                ('journal_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journalnote_grade', to='webapp.JournalNote', verbose_name='Оценка за занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_grade', to=settings.AUTH_USER_MODEL, verbose_name='Оценка студенту')),
            ],
        ),
    ]
