# Generated by Django 2.2 on 2020-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_journalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalgrade',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание'),
        ),
    ]
