# Generated by Django 2.2 on 2020-03-06 05:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0025_auto_20200303_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalgrade',
            unique_together={('journal_note', 'grade', 'student')},
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
