# Generated by Django 2.2 on 2020-03-06 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0026_auto_20200306_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalgrade',
            unique_together={('journal_note', 'student')},
        ),
    ]
