# Generated by Django 2.2 on 2020-03-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20200306_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalgrade',
            unique_together=set(),
        ),
    ]
